# FetchIt Configuration
# This file is used by FetchIt to manage GitOps deployments

# Dynamic Configuration Reload - allows config changes without container restart
configReload:
  schedule: "*/5 * * * *"
  configUrl: https://raw.githubusercontent.com/ddemlow/fleet-manager-gitops/master/fetchit/fetchit-config.yaml

targetConfigs:
- url: https://github.com/ddemlow/fleet-manager-gitops
  branch: master
  systemd:
  - name: demo-services
    targetPath: fetchit/systemd
    root: true
    enable: true
    schedule: "*/2 * * * *"
global:
  logLevel: info
  maxRetries: 3
  retryDelay: "30s"