# FetchIt Configuration
# This file is used by FetchIt to manage GitOps deployments

# Dynamic Configuration Reload - allows config changes without container restart
configReload:
  schedule: "*/5 * * * *"
  configUrl: https://raw.githubusercontent.com/ddemlow/fleet-manager-gitops/master/fetchit/fetchit-config.yaml

targetConfigs:
- url: https://github.com/ddemlow/fleet-manager-gitops
  branch: master
  fileTransfer:
  - name: fetchit-config
    targetPath: fetchit/fetchit-config.yaml
    destinationDirectory: /opt/fetchit
    schedule: "*/5 * * * *"
  systemd:
  - name: quadlet-services
    targetPath: fetchit/containers
    destinationDirectory: /etc/containers/systemd
    schedule: "*/2 * * * *"
  kube:
  - name: kube-demo
    targetPath: fetchit/kube
    schedule: "*/4 * * * *"
  ansible:
  - name: ansible-demo
    targetPath: fetchit/ansible
    sshDirectory: /root/.ssh
    schedule: "*/6 * * * *"
global:
  logLevel: info
  maxRetries: 3
  retryDelay: "30s"