# FetchIt Configuration for GitOps Container Management
# This configures FetchIt to manage containers from the fleet-manager-gitops repository

targetConfigs:
- url: https://github.com/ddemlow/fleet-manager-gitops
  branch: master
  fileTransfer:
  - name: fetchit-config
    targetPath: fetchit/fetchit-config.yaml
    destinationDirectory: /opt/fetchit
    schedule: "*/5 * * * *"  # Check every 5 minutes for config changes
  raw:
  - name: demo-containers
    targetPath: fetchit/containers
    schedule: "*/2 * * * *"  # Check every 2 minutes for container definitions
  systemd:
  - name: web-services
    targetPath: fetchit/systemd
    schedule: "*/3 * * * *"  # Check every 3 minutes for systemd services

# Global settings
global:
  logLevel: info
  maxRetries: 3
  retryDelay: "30s"
