# FetchIt Configuration
# This file is used by FetchIt to manage GitOps deployments

# Dynamic Configuration Reload - allows config changes without container restart
configReload:
  schedule: "*/5 * * * *"
  configUrl: https://raw.githubusercontent.com/ddemlow/fleet-manager-gitops/master/fetchit/fetchit-config.yaml

targetConfigs:
- url: https://github.com/ddemlow/fleet-manager-gitops
  branch: master
  fileTransfer:
  - name: fetchit-config
    targetPath: fetchit/fetchit-config.yaml
    destinationDirectory: /opt/fetchit
    schedule: "*/5 * * * *"
  - name: timer-overrides
    targetPath: fetchit/timer-configs
    destinationDirectory: /etc/systemd/system
    schedule: "*/10 * * * *"
  raw:
  - name: demo-containers
    targetPath: fetchit/containers
    schedule: "*/2 * * * *"
    pullImage: true
global:
  logLevel: info
  maxRetries: 3
  retryDelay: "30s"