version: "1"
type: "Application"
metadata:
  name: "gitops-example-vm"
  description: "Example virtual machine deployment - touch"
  clusterGroups:
    - DDvsns
  labels:
    - development

spec:
  assets:
    - name: test-disk
      type: virtual_disk
      format: raw
      url: https://storage.googleapis.com/demo-bucket-lfm/netboot.xyz.img
  resources:
    - name: gitops-example-vm
      type: virdomain
      spec:
        description: A simple VM for testing - gitops demo pr 2 
        cpu: 1
        memory: "2147483648"
        machine_type: bios
        storage_devices:
          - name: cdrom1
            type: ide_cdrom
            boot: 1
          - name: disk1
            source: test-disk
            boot: 2
          - name: disk2
            type: virtio_disk
            capacity: 100000000000
        network_devices:
          - name: nic1
            type: virtio
        tags:
          - kraken
          - test
        state: running #running or shutoff - comments preserved 
