type: Application
version: '1'
metadata:
  description: K0s Kubernetes cluster deployment
  clusterGroups:
    - DDGroup
  labels:
    - app:kubernetes
    - environment:production
    - team:platform
  name: k0s-demo
spec:
  assets:
    - name: ubuntu_focal
      type: virtual_disk
      format: raw
      url: "https://storage.googleapis.com/demo-bucket-lfm/focal-server-cloudimg-amd64.img"


  resources: 
    - type: "virdomain"
      name: "gitops-k0s-single-{{clusterName}}"
      spec:
        description: "name {{clusterName}} id {{clusterId}}"
        cpu: 2
        memory: "2147483648" #2GB in bytes
        machine_type: "uefi"
        storage_devices:
          - name: "bootdisk"
            type: "virtio_disk"
            source: "ubuntu_focal"
            boot: 1
            capacity: 42949672960  # 40 GB
        network_devices:
          - name: eth0
            type: virtio

        tags:
          - ubuntu
          - "{{clusterName}}"
          - kraken
          - gitops
        state: running

        cloud_init_data:
          user_data: |
            #cloud-config
            password: "password"
            chpasswd: { expire: False }
            ssh_pwauth: True
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
            disable_root: false
            ssh_pwauth: True
            ssh_import_id:  gh:ddemlow
            users:
            - name: user
              groups: [wheel]
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              ssh-authorized-keys:
                - ssh-rsa ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
            chpasswd:
              list: |
                dave:password
              expire: false
            packages:
              - qemu-guest-agent
              - git
              - curl
              - wget
              - htop
              - nano
              - jq
            write_files:
              - content: "{{ inventory_hostname }}"
                path: /clusterip.txt
              - path: /etc/systemd/system/getty@tty1.service.d/override.conf
                content: |
                  [Service]
                  # Override getty@.service for tty1 to enable autologin
                  ExecStart=
                  ExecStart=-/sbin/agetty --autologin user --noclear %I $TERM
                permissions: '0644'
            bootcmd:
              - [ sh, -c, 'sudo echo GRUB_CMDLINE_LINUX="nomodeset" >> /etc/default/grub' ]
              - [ sh, -c, 'sudo echo GRUB_GFXPAYLOAD_LINUX="1024x768" >> /etc/default/grub' ]
              - [ sh, -c, 'sudo echo GRUB_DISABLE_LINUX_UUID=true >> /etc/default/grub' ]
              - [ sh, -c, 'sudo update-grub' ]
            runcmd:
              - [ systemctl, restart, --no-block, qemu-guest-agent ]
              - curl -sSf https://get.k0s.sh | sh
              - k0s install controller --single
              - k0s start
              - sleep 60
              - export PATH=$PATH:/usr/local/bin
              - k0s kubectl create ns demo2
              - k0s kubectl config set-context --current --namespace=demo2
              - cd /tmp && git clone https://github.com/GoogleCloudPlatform/microservices-demo
              - cd /tmp/microservices-demo
              - k0s kubectl apply -f ./release/kubernetes-manifests.yaml
              - k0s kubectl get pods
              - k0s kubectl get service frontend-external
          meta_data: |
            dsmode: local
            local-hostname: "gitops-k0s-{{clusterName}}"
