type: Application
version: '1'
metadata:
  description: K0s Kubernetes cluster deployment
  labels:
    app: kubernetes
    environment: production
    team: platform
  name: k0s-node
spec:
  assets:
    - name: k3s-disk
      format: raw
      type: virtual_disk
      url: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img


  resources: 
    - type: "virdomain"
      name: "gitops-k0s-{{clusterName}}"
      spec:
        description: "name {{clusterName}} id {{clusterId}}"
        cpu: 2
        memory: "2147483648" #2GB in bytes
        machine_type: "uefi"
        storage_devices:
          - name: "bootdisk"
            type: "virtio_disk"
            source: "k3s-disk"
            boot: 1
            capacity: 42949672960  # 40 GB
        network_devices:
          - name: eth0
            type: virtio

        tags:
          - ubuntu
          - "{{clusterName}}"
          - kraken
          - gitops
          - *vmname
        state: running

        cloud_init_data:  # note microos does not support write_files: as an immutable os
          user_data: |
            #cloud-config
            password: "password"
            chpasswd: { expire: False }
            ssh_pwauth: True
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
            disable_root: false
            ssh_pwauth: True
            ssh_import_id:  gh:ddemlow
            users:
            - name: dave
              groups: [wheel]
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              ssh-authorized-keys:
                - ssh-rsa ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
            chpasswd:
              list: |
                dave:password
              expire: false
