version: "1"
type: "Application"
metadata:
  name: "nginx-deployment"
  description: "Nginx web server deployment 5 (GH Actions test)"
  clusterGroups:
    - DDvsns
  labels:
    environment: "production"
    team: "web"
    app: "nginx"
spec:
  assets:
    - name: test-disk
      type: virtual_disk
      format: iso
      url: https://releases.ubuntu.com/24.04/ubuntu-24.04.2-live-server-amd64.iso