version: "1"
type: "Application"
metadata:
  name: "nginx-deployment"
  description: "Nginx web server deployment"
  labels:
    environment: "production"
    team: "web"
    app: "nginx"
spec:
  assets:
    - name: "nginx-disk"
      type: "virtual_disk"
      format: "qcow2"
      size: "10Gi"
      url: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    - name: "nginx-vm"
      type: "virtual_machine"
      vcpus: 1
      memory: "2Gi"
      disks:
        - name: "nginx-disk"
          size: "10Gi"
      networks:
        - name: "default"
          type: "bridge"
      userData: |
        #cloud-config
        users:
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7... # Your SSH key here
        packages:
          - nginx
          - curl
        runcmd:
          - systemctl enable nginx
          - systemctl start nginx
          - echo "<h1>Hello from GitOps!</h1>" > /var/www/html/index.html
          - systemctl reload nginx
