apiVersion: v1
kind: Pod
metadata:
  name: demo-web
spec:
  containers:
  - name: demo-container
    image: registry.k8s.io/nginx-slim:0.9
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: demo-content
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: demo-content
    hostPath:
      path: /var/www/demo
      type: Directory
  restartPolicy: Always
