apiVersion: v1
kind: Pod
metadata:
  name: demo-web
spec:
  containers:
  - name: demo-container
    image: registry.k8s.io/nginx-slim:0.8
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: demo-content
      mountPath: /usr/share/nginx/html
      readOnly: true
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command: ["/bin/sh"]
    args: ["-c", "nginx -g 'daemon off;'"]
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
  volumes:
  - name: demo-content
    hostPath:
      path: /var/www/demo
      type: Directory
  restartPolicy: Always
