apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-demo-config
data:
  APP_NAME: "Kube Demo (Kubernetes Method)"
  APP_COLOR: "purple"
  CONTAINER_PORT: "8082"
  DEPLOYMENT_METHOD: "kubernetes"
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-demo-pod
spec:
  containers:
  - name: kube-demo
    image: docker.io/mmumshad/simple-webapp-color:latest
    ports:
    - containerPort: 8080
      hostPort: 8082
    envFrom:
    - configMapRef:
        name: kube-demo-config
        optional: false
