apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-demo-config
data:
  APP_NAME: "GitOps Kube Demo"
  APP_COLOR: "green"
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-demo-pod
spec:
  containers:
  - name: kube-demo
    image: registry.k8s.io/nginx-slim:0.7
    ports:
    - containerPort: 80
      hostPort: 8082
    envFrom:
    - configMapRef:
        name: kube-demo-config
        optional: false
