apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  containers:
  - name: nginx-demo
    image: registry.k8s.io/nginx-slim:0.8
    ports:
    - containerPort: 80
      hostPort: 8081
    volumeMounts:
    - name: nginx-content
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: nginx-content
    hostPath:
      path: /var/www/nginx
      type: Directory
  restartPolicy: Always
