version: "1"
type: "ContainerDefinition"
metadata:
  name: "demo"
  clusterGroups:
    - DDvsns
  labels:
    - scruntime
    - nginx

spec:
  runtime:
    vcpus: 2
    memory: "2Gi"
    disk:
      capacity: "40Gi"
  containers:
    - name: "nginx"
      image: "docker.io/library/nginx:1.27-alpine"
      ports:
        - "80:80"
      mounts:
        - hostPath: "/var/edge/www"
          mountPath: "/usr/share/nginx/html"
          selinuxRelabel: true
      env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"

  content:
    - path: "/var/edge/www/index.html"
      mode: "0644"
      data: |
        <!doctype html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Welcome - {{clusterName}}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style>
              :root { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, sans-serif; }
              body { margin: 2rem; line-height: 1.5; }
              .wrap { max-width: 52rem; }
              h1 { margin-bottom: .25rem; }
              .meta { color: #555; margin-bottom: 1rem; }
              code { background: #f4f4f4; padding: .125rem .375rem; border-radius: .25rem; }
              .card { border: 1px solid #e6e6e6; border-radius: .5rem; padding: 1rem; }
            </style>
          </head>
          <body>
            <div class="wrap">
              <h1>Welcome to nginx on MicroOS - Scale Computing Runtime gitops demo compile</h1>
              <p class="meta">This node is serving a custom page from a bind-mounted volume.</p>
              <div class="card">
                <p><strong>Cluster:</strong> <code>{{clusterName}}</code></p>
                <p><strong>Cluster ID:</strong> <code>{{clusterId}}</code></p>
              </div>
              <p>Content path: <code>/var/edge/www/index.html</code> → mounted into <code>/usr/share/nginx/html</code>.</p>
            </div>
          </body>
        </html>