version: "1"
type: "ContainerDefinition"
metadata:
  name: "nginx-simplified"
  clusterGroups:
    - DDvsns
  labels:
    - example
    - nginx

spec:
  cloudInit:
    users:
      - name: dave
        groups: [wheel]
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        sshAuthorizedKeys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
          - github:daveddemlow
  containers:
    - name: "nginx"
      image: "docker.io/library/nginx:1.27-alpine"
      ports:
        - "80:80"
      mounts:
        - hostPath: "/var/edge/www"
          mountPath: "/usr/share/nginx/html"
          selinuxRelabel: true
      env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"

  content:
    - path: "/var/edge/www/index.html"
      mode: "0644"
      data: |
        <!doctype html>
        <html>
          <body>
            <h1>Hello from nginx v1.27 pinned</h1>
          </body>
        </html>

