version: "1"
type: "RuntimeConfiguration"
metadata:
  name: "default-runtime"

spec:
  cloudInit:
    ssh:
      passwordAuth: true
      disableRoot: false
    users:
      - name: user
        groups: [wheel]
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        sshAuthorizedKeys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDihWWhjoPj8KVLtdLDwNJQ71zi9An0iUFjefRWu2Eju ddemlow@scalecomputing.com
          - github:daveddemlow
    chpasswd:
      list: |
        user:password
      expire: false
  runtime:
    vcpus: 2
    memory: "2Gi"
    disk:
      name: "rootdisk"
      capacity: "40Gi"
      format: "raw"
      url: "https://pm-westfield.s3.us-east-2.amazonaws.com/openSUSE-MicroOS.x86_64-ContainerHost-OpenStack-Cloud.raw"
  network:
    - name: "eth0"
      type: "virtio"


