# Application Manifest Template
# Copy this template to create new applications
# Required fields: name, description, lifecycle, clusterGroups

type: Application
version: '1'
metadata:
  # REQUIRED: Application name (must be unique)
  name: "my-application"
  
  # REQUIRED: Description of the application
  description: "Description of what this application does"
  
  # REQUIRED: Lifecycle state (draft, testonly, production, undeploy)
  lifecycle: "draft"
  
  # REQUIRED: Target cluster groups
  clusterGroups:
    - "DDvsns"
  
  # OPTIONAL: Labels for categorization
  labels:
    - "team-backend"
    - "environment-production"
  
  # OPTIONAL: Test cluster group for PR testing (defaults to dd_szt15b)
  testClusterGroup: "dd_szt15b"

spec:
  # Application assets (disks, ISOs, etc.)
  assets:
    - name: "my-disk"
      type: "virtual_disk"
      format: "raw"
      url: "https://example.com/disk.img"
  
  # Application resources (VMs, networks, etc.)
  resources:
    - name: "my-vm"
      type: "virdomain"
      spec:
        description: "My virtual machine"
        cpu: 2
        memory: "4294967296"  # 4GB in bytes
        machine_type: "uefi"
        
        # Storage devices
        storage_devices:
          - name: "bootdisk"
            type: "virtio_disk"
            source: "my-disk"
            boot: 1
            capacity: 42949672960  # 40GB
        
        # Network devices
        network_devices:
          - name: "eth0"
            type: "virtio"
        
        # Tags for organization
        tags:
          - "my-app"
          - "production"
        
        # VM state
        state: "running"
        
        # OPTIONAL: Cloud-init configuration
        cloud_init_data:
          user_data: |
            #cloud-config
            # Add your cloud-init configuration here
            users:
              - name: "admin"
                groups: ["wheel"]
                sudo: "ALL=(ALL) NOPASSWD:ALL"
