name: Enhanced Deploy to Fleet Manager

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target_applications:
        description: 'Specific applications to deploy (comma-separated, leave empty for all)'
        required: false
        type: string
      skip_deployment_trigger:
        description: 'Update applications but do not trigger deployments'
        required: false
        type: boolean
        default: false
      only_compile:
        description: 'Only compile manifests, do not deploy'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Compile manifests (if needed)
        run: |
          python scripts/compile_manifests.py
      
      - name: Deploy to Fleet Manager
        env:
          SC_FM_APIKEY: ${{ secrets.SC_FM_APIKEY }}
          FLEET_MANAGER_API_URL: ${{ secrets.FLEET_MANAGER_API_URL }}
          TARGET_APPLICATIONS: ${{ github.event.inputs.target_applications }}
          SKIP_DEPLOYMENT_TRIGGER: ${{ github.event.inputs.skip_deployment_trigger }}
          ONLY_COMPILE: ${{ github.event.inputs.only_compile }}
        run: |
          python scripts/deploy.py
      
      - name: Show deployment summary
        if: always()
        run: |
          echo "📊 Deployment completed!"
          echo "Check the logs above for detailed results."
