name: Generate Documentation

on:
  push:
    branches: [ master ]
    paths:
      - 'manifests/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate documentation
      run: |
        echo "📚 Generating application documentation..."
        python scripts/generate-docs.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet docs/; then
          echo "No documentation changes to commit"
        else
          git add docs/
          git commit -m "📚 Auto-update application documentation"
          git push
        fi
